class Mm2Prop:
    """
    Custom props converted from the real Midtown Madness 2 `.pkg` prop meshes (so the MM2 city
    import places the ACTUAL MM2 model, not an MM1 placeholder). Each value is the game prop id;
    matching assets live under `resources/editor/custom/MM2_PROPS/{MESHES,TUNE,TEXTURES}`,
    generated by `src/game/mapgen/mm2/pkg_to_bms.py` from `MM2_GAME/mm2core/geometry/*.pkg`.
    """
    LAMP      = "mm2lamp"      # sp_lightstreet_rt_f  (banner street lamp)
    DUMPSTER  = "mm2dump"      # sp_dumpstr_f
    BENCH     = "mm2bench"     # sp_benchwood_f
    PALM      = "mm2palm"      # sp_treepalm4_f       (no MM1 palm exists -> this is the win)
    TREE      = "mm2tree"      # sp_tree1_s           (real MM2 tree billboard, alpha cutout)
    TREE6     = "mm2tree6"     # sp_tree6_s           (the other MM2 tree)
    BARRICADE = "mm2barricade" # sp_barricadewood_f   (real wooden barricade)
    STOP        = "mm2stop"        # sp_stop_f          (real stop sign, alpha face)
    NOENTER     = "mm2noenter"     # sp_noenter_f
    WRONGWAY    = "mm2wrongway"    # sp_wrongwayfw
    BOXBARREL   = "mm2boxbarrel"   # sp_stackboxbarrel_f
    CRASHBARREL = "mm2crashbarrel" # sp_crashbarrelgroup_f
    BOXCARD     = "mm2boxcard"     # sp_stackboxcard_f
    CLEAT       = "mm2cleat"       # sp_cleat_f         (dock cleat -- was skipped, now real)
    MAIL        = "mm2mail"        # sp_mailbox_f
    HOTDOG      = "mm2hotdog"      # sp_hotdogcart_f    (detailed food cart)
    HILLWARN    = "mm2hillwarn"    # sp_hillwarn_f
    EXIT_TB     = "mm2exittb"      # sp_transbayexit_f  (freeway exit signs)
    EXIT_MAR    = "mm2exitmar"     # sp_marinexit_f
    EXIT_CC     = "mm2exitcc"      # sp_civcentrexit_f
    EXIT_GG     = "mm2exitgg"      # sp_ggexit_f
    EXIT_EMB    = "mm2exitemb"     # sp_embarcexit_f
    GDELLI      = "mm2gdelli"      # np_ghirardelli_f   (Ghirardelli landmark sign)
    BANNER_RED  = "mm2bannerred"   # cp_banrred_f
    BANNER_BLU  = "mm2bannerblu"   # cp_banrblu_f
    BANNER_YEL  = "mm2banneryel"   # cp_banryel_f
    # ── London-specific props (city/london/props.pathset) ────────────────────────────
    BOLLARD_STONE = "mm2bollardstone"  # sp_bollard_stone_l
    BOLLARD_BLACK = "mm2bollardblack"  # sp_bollard_black_l
    LIGHT_PARK    = "mm2lightpark"     # sp_lightpark_f
    DUMPSTER_L    = "mm2dumpl"         # sp_dumpstr_l
    CONE_L        = "mm2conel"         # sp_cone_l
    OAK           = "mm2oak"           # sp_oaktree1_s   (oak tree)
    BOXES4        = "mm2boxes4"        # sp_stackboxes_4_l
    LIGHT_THAMES  = "mm2lightthames"   # sp_lightthames_l
    PILASTER      = "mm2pilaster"      # sp_pilaster_l
    CENOTAPH      = "mm2cenotaph"      # sp_cenotaph_gen_l
    BARREL_WOOD   = "mm2barrelwood"    # sp_barrelwood_l
    FENCE         = "mm2fence"         # wp_buck_fence_l
    EROS          = "mm2eros"          # op_eros_l        (the Piccadilly Eros statue)
